server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: hankyu
    username: hankyu
    url: jdbc:mariadb://localhost:3306/security1

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 50964896759-91fhej65e9bh0m99040hf79d9jdco71h.apps.googleusercontent.com
            client-secret: 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
            scope:
              -email
              -profile